import Head from 'next/head';
import { EmblaCarousel } from '../components/EmblaCarousel';

export default function Home() {
  return (
    <div className="h-screen w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-10">
        <EmblaCarousel />
      </div>
    </div>
  );
}
